openapi: 3.0.3
info:
  title: AI Travel Planner API
  version: 0.1.0
  description: API 草案（包含 trips, generate, itinerary_items, expenses 等）
servers:
  - url: https://api.example.com
    description: Production
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Trip:
      type: object
      properties:
        id:
          type: string
          format: uuid
        owner_id:
          type: string
        title:
          type: string
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
        estimated_budget:
          type: number
        estimated_budget_consumed:
          type: number
        estimated_budget_remaining:
          type: number
        currency:
          type: string
        status:
          type: string
        days:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
              items:
                type: array
                items:
                  $ref: '#/components/schemas/ItineraryItem'
        expenses:
          type: array
          items:
            $ref: '#/components/schemas/Expense'
        metadata:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ItineraryItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        trip_id:
          type: string
        day_index:
          type: integer
        date:
          type: string
          format: date
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        title:
          type: string
        type:
          type: string
        location:
          type: object
          properties:
            lat:
              type: number
            lng:
              type: number
            address:
              type: string
        est_cost:
          type: number
        actual_cost:
          type: number
        currency:
          type: string
        sequence:
          type: integer
        notes:
          type: string
    Expense:
      type: object
      properties:
        id:
          type: string
          format: uuid
        trip_id:
          type: string
        itinerary_item_id:
          type: string
        user_id:
          type: string
        payer_id:
          type: string
        status:
          type: string
        payment_method:
          type: string
        vendor:
          type: string
        receipt_url:
          type: string
        split:
          type: object
        created_at:
          type: string
          format: date-time
        amount:
          type: number
        currency:
          type: string
        category:
          type: string
        date:
          type: string
          format: date
        note:
          type: string
paths:
  /api/trips:
    post:
      summary: Create trip
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                start_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                estimated_budget:
                  type: number
                currency:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/generate:
    post:
      summary: Submit generation job
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trip_id:
                  type: string
                user_input:
                  type: string
                mode:
                  type: string
                  enum: [draft, detailed]
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
  /api/generate/{job_id}:
    get:
      summary: Get job status
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: job_id
          schema:
            type: string
      responses:
        '200':
          description: Job status
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                  status:
                    type: string
                  result:
                    type: object
  /api/trips/{id}:
    get:
      summary: Get trip details
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
        - in: query
          name: include
          schema:
            type: string
            enum: [items,expenses,attachments]
      responses:
        '200':
          description: Trip detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
              examples:
                sampleTrip:
                  summary: Example trip with items and expenses
                  value:
                    status: "ok"
                    data:
                      trip:
                        id: "trip_123"
                        owner_id: "user_abc"
                        title: "东京亲子美食游"
                        start_date: "2025-12-10"
                        end_date: "2025-12-15"
                        estimated_budget: 10000
                        currency: "CNY"
                        status: "generated"
                        days:
                          - date: "2025-12-10"
                            items:
                              - id: "item_1"
                                type: "flight"
                                title: "北京 - 东京"
                                start: "2025-12-10T08:00:00+08:00"
                                end: "2025-12-10T12:30:00+09:00"
                                location: null
                                est_cost: 2000
                                actual_cost: 2000
                                currency: "CNY"
                                notes: "建议选择直飞"
                              - id: "item_2"
                                type: "poi"
                                title: "浅草寺"
                                start: "2025-12-10T15:00:00+09:00"
                                end: "2025-12-10T16:30:00+09:00"
                                location:
                                  lat: 35.7148
                                  lng: 139.7967
                                  address: "浅草 2-3-1"
                                est_cost: 0
                                actual_cost: 120
                                currency: "CNY"
                                notes: "适合带孩子"
                        expenses:
                          - id: "exp_1"
                            itinerary_item_id: "item_2"
                            user_id: "00000000-0000-0000-0000-000000000001"
                            payer_id: "00000000-0000-0000-0000-000000000001"
                            amount: 120
                            currency: "CNY"
                            category: "meal"
                            date: "2025-12-10"
                            note: "浅草拉面"
                            vendor: "浅草拉面店"
                            payment_method: "credit_card"
                            status: "cleared"
                            recorded_via: "manual"
                        estimated_budget_consumed: 2120
                        estimated_budget_remaining: 7880
                        metadata: {}
                        created_at: "2025-10-31T12:00:00Z"
                        updated_at: "2025-10-31T12:10:00Z"
  /api/trips/{id}/itinerary_items:
    post:
      summary: Create itinerary item
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItineraryItem'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItineraryItem'
  /api/trips/{id}/expenses:
    post:
      summary: Add expense
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expense'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expense'
